### ISSUE TITLE
Bikin Flowchart Aplikasi

### ISSUE THREAD

**Issue by Hasban-Fardani** [Hasban-Fardani/datakeun#1]

**Comment by Hasban-Fardani** [comment]
link hasil:
https://whimsical.com/erd-entity-relational-database-datakeun-JQvuscLmdtHMDTJD7wjsCR

**Comment by Wyaaattt** [comment]
Aduh bro hasban thank you udah bantuin

**Comment by Hasban-Fardani** [comment]
harus di revisi masbro

**Comment by Hasban-Fardani** [comment]
oke done
